### ISSUE TITLE
Apple News Errors

### ISSUE THREAD

**Issue by Orzolek** [alleyinteractive/apple-news#627]
Hello!

Really need your advice. We are getting the following errors. The site is built with Qode Interactive: Bridge WP theme using WPBakery Page Builder.

Would love to know how to fix them.

> Channel content contains exposed unicode, HTML, or XML.
> Articles contain repeating text.

Many thanks in advance

**Comment by Orzolek** [comment]
Also now shows : There has been an error with the API: NOT_ALLOWED

**Comment by kevinfodness** [comment]
Repeating text may be caused by not customizing the excerpt, which can cause the first paragraph to repeat. I'd recommend either customizing the excerpt or disabling the Intro component in the plugin settings.

For the other error, are you using HTML format? I'd recommend using HTML over markdown, as it is more forgiving, and is currently Apple's preferred format.

**Comment by Orzolek** [comment]
Thanks for the info. I've had intro set to inactive and I'm using HTML, but still getting the articles rejected. Is there anything else I can do?

**Comment by kevinfodness** [comment]
Can you copy the content from your article and either paste it here or link to a pastebin? I can attempt to reproduce on my end.

**Comment by Orzolek** [comment]
Hi, thanks again. Sorry to sound like a novice, do you mean the code text of the original post?

**Comment by kevinfodness** [comment]
If you're using the classic editor (TinyMCE) then you just go to the Text tab and copy/paste everything that's there. If you're using the new block editor (Gutenberg) that shipped with WordPress 5, then you'll need to copy all of the block content. Alternately, if you have database access, you could get what is in the `post_content` column for that post, as whatever is in `post_content` is ultimately what the plugin looks at.

**Comment by Orzolek** [comment]
Thanks, Kevin. just making sure ;) I'm using WPBakery...

[vc_row css_animation="" row_type="row" use_row_as_full_screen_section="no" type="full_width" angled_section="no" text_align="left" background_image_as_pattern="without_pattern"][vc_column][vc_column_text]

Pre-season game number one for the newly rebranded Aston Villa Women, a new name and branding with a new look team as eight players have departed, while so far seven have arrived at the club. Before the game they announced that Shania Hayles, Natalie Pugh and Charlotte Greengrass had also joined us for the season. Between the fans that arrived there was a buzz that this season could be something special as we push towards improving on Gemma Davies first season in charge.

After catching up with a few of the parents and staff it was time to make the way out to the stands to once again cheer on our Women in Claret and Blue. The teams started to make their way out in the training gear as we wait for the kits on the squad to be finalised. After a off season of waiting for news and getting to get behind our team the ref blew the whistle as the game kicked off.

Kerri Welsh took our first touch of the 19/20 season as she kicked off and we changed our chants to Women and not Ladies (a few fluff ups happened during the game but hey it's pre-season) straight away Villa got into the game as they moved the ball around well, Sophie Haywood showed the guns and obviously sent fear into the Stoke defenders hearts.

A fast start within 2 minutes saw Hayles open her account and Villa Women’s account as Melissa Johnson pulled the ball back to Hayles who struck the ball first time into the top corner leaving the Stoke keeper no chance and getting Villa off to a cracking start as it became 1-0. 

[/vc_column_text][vc_empty_space][/vc_column][/vc_row][vc_row css_animation="" row_type="row" use_row_as_full_screen_section="no" type="full_width" angled_section="no" text_align="left" background_image_as_pattern="without_pattern"][vc_column width="1/6"][/vc_column][vc_column width="2/3"][vc_raw_html]JTNDYmxvY2txdW90ZSUyMGNsYXNzJTNEJTIydHdpdHRlci10d2VldCUyMiUyMGRhdGEtbGFuZyUzRCUyMmVuJTIyJTNFJTNDcCUyMGxhbmclM0QlMjJlbiUyMiUyMGRpciUzRCUyMmx0ciUyMiUzRVdvdyUyMSUyMCUzQ2ElMjBocmVmJTNEJTIyaHR0cHMlM0ElMkYlMkZ0d2l0dGVyLmNvbSUyRm1lbGdlbWpvaG5zb24lM0ZyZWZfc3JjJTNEdHdzcmMlMjU1RXRmdyUyMiUzRSU0ME1lbEdlbUpvaG5zb24lM0MlMkZhJTNFJTIwdGFrZSUyMGElMjBib3cuJTIwJUYwJTlGJTkxJThGJUYwJTlGJThGJUJDJTIwJTNDYSUyMGhyZWYlM0QlMjJodHRwcyUzQSUyRiUyRnR3aXR0ZXIuY29tJTJGaGFzaHRhZyUyRlNlZUlzUm9hciUzRnNyYyUzRGhhc2glMjZhbXAlM0JyZWZfc3JjJTNEdHdzcmMlMjU1RXRmdyUyMiUzRSUyM1NlZUlzUm9hciUzQyUyRmElM0UlMjAlM0NhJTIwaHJlZiUzRCUyMmh0dHBzJTNBJTJGJTJGdHdpdHRlci5jb20lMkZoYXNodGFnJTJGQVZGQyUzRnNyYyUzRGhhc2glMjZhbXAlM0JyZWZfc3JjJTNEdHdzcmMlMjU1RXRmdyUyMiUzRSUyM0FWRkMlM0MlMkZhJTNFJTIwJTIwJTNDYSUyMGhyZWYlM0QlMjJodHRwcyUzQSUyRiUyRnR3aXR0ZXIuY29tJTJGQVZXRkNPZmZpY2lhbCUzRnJlZl9zcmMlM0R0d3NyYyUyNTVFdGZ3JTIyJTNFJTQwQVZXRkNPZmZpY2lhbCUzQyUyRmElM0UlMjAlM0NhJTIwaHJlZiUzRCUyMmh0dHBzJTNBJTJGJTJGdC5jbyUyRjdqcGhBZEFEMFolMjIlM0VwaWMudHdpdHRlci5jb20lMkY3anBoQWRBRDBaJTNDJTJGYSUzRSUzQyUyRnAlM0UlMjZtZGFzaCUzQiUyMFNpbmNlJTIwNzElMjAlMjglNDBTaW5jZTcxQmxvZyUyOSUyMCUzQ2ElMjBocmVmJTNEJTIyaHR0cHMlM0ElMkYlMkZ0d2l0dGVyLmNvbSUyRlNpbmNlNzFCbG9nJTJGc3RhdHVzJTJGMTE1MzI4NzMyMDc4MDY2MDczNiUzRnJlZl9zcmMlM0R0d3NyYyUyNTVFdGZ3JTIyJTNFSnVseSUyMDIyJTJDJTIwMjAxOSUzQyUyRmElM0UlM0MlMkZibG9ja3F1b3RlJTNFJTBBJTNDc2NyaXB0JTIwYXN5bmMlMjBzcmMlM0QlMjJodHRwcyUzQSUyRiUyRnBsYXRmb3JtLnR3aXR0ZXIuY29tJTJGd2lkZ2V0cy5qcyUyMiUyMGNoYXJzZXQlM0QlMjJ1dGYtOCUyMiUzRSUzQyUyRnNjcmlwdCUzRSUwQQ==[/vc_raw_html][/vc_column][vc_column width="1/6"][/vc_column][/vc_row][vc_row css_animation="" row_type="row" use_row_as_full_screen_section="no" type="full_width" angled_section="no" text_align="left" background_image_as_pattern="without_pattern"][vc_column][vc_column_text]

The next action saw Leanne Robinson in the 7th minute go down in a challenge that saw her have to come off as she fractured her wrist in an unfortunate accident. A lot of the play was Villa on the ball as they played some nice football keeping the ball and moving it around into the Stoke half. Cassie Hyde was working hard as she tackled Sophie Haywood as she was about to pull the trigger, but Cassie seemed to be all over the place at the back as she was always there to keep out our attackers.

The next chance also came for Villa as we broke forward and pushed Stoke back but the effort just fizzed past the post as we started to build some pressure on the Stoke goal once again. It wouldn’t take Melissa Johnson to prove exactly what we knew as she drove at the Stoke defence and unleashed a cracking shot as it went straight into the top corner with precision and power giving Villa Women the 2-0 lead.

[/vc_column_text][vc_empty_space][/vc_column][/vc_row][vc_row css_animation="" row_type="row" use_row_as_full_screen_section="no" type="full_width" angled_section="no" text_align="left" background_image_as_pattern="without_pattern"][vc_column][vc_single_image image="2783" img_size="full" add_caption="yes" qode_css_animation=""][/vc_column][/vc_row][vc_row css_animation="" row_type="row" use_row_as_full_screen_section="no" type="full_width" angled_section="no" text_align="left" background_image_as_pattern="without_pattern"][vc_column][vc_column_text]

No surprises how this game was going that the next chance fell to Villa once again as the Stoke keeper once again came to the rescue as Kerri Welsh sitting deep hit a thunderbolt that looked destined for the top corner as the Stoke keeper dived outstretched and tip it over the bar with an incredible save. Once again the wing play was proving something special with Haywood and Franklin linking up and Greengrass and Hayles linking up which drove us forward and as Mel Johnson broke past the defence and put the ball across to Sophie Haywood who was read to tap in the Stoke keeper read it well and got across to stop the cross coming in. But even with Stoke defending well and the keeper pulling off the saves we went into the break with a 3-0 lead.

Just before the break Mel Johnson got her second of the game as Sophie Haywood drove down the wing and pulled the ball back to the boot of Mel Johnson as she shaped herself and hit the ball first time not giving the keeper chance to react as the ball hit the back of the net as we took a 3-0 lead into the half time break. The combination of Marisa Ewers and Amy West looks something to behold as both work so hard to win the ball back and both can pin point a ping to each wing to get us going forward at any time.

A lot of changes with Stoke making a fair few and Villa had brought on Nadine Hanssen, Phoebe Warner, Jodie Hutton and Natalie Pugh all getting minutes in the second half as each and every player would need minutes to get fit ready for the new upcoming season. But also as well as giving people minutes it also gave Gemma the chance to try players in different positions as Amy West switched back to left back which she was part of the Great Wall of China that Tony Xia once tweeted about and giving Ella Franklin the chance to play in the centre.

Villa started the second half as they had started the first half on the front foot as the first chance fell to Villa as Mel Johnson used her pace to get past the Stoke defence and as she hit it low and hard the Stoke keeper like a cat dived down to push it past the post keeping the score at 3-0. Stoke created a chance from outside the box but it didn’t cause Sian Rogers took much trouble as Jade Richards and Elisha N’Dow wasn’t giving away anything at the back, our double trouble team.

Mel Johnson once again was driving at the goal as she pulled it across the box and a moment that Hollie Gibson might of nearly wanted to forget as her clearance had the Stoke keeper scrambling (We still wish we had Hollie with us but no matter where she is we’ll love her) but the Stoke keeper kept it out and as the ball fell to Phoebe Warner she tried to stab it home but somehow the Stoke keeper pulled off the double save keeping the score at 3-0. Nadine Hanssen must of had some anger to let out as she destroyed the paint on the crossbar as she moved into position and unleashed a shot that nearly took the crossbar off but unfortunately the ball cannoned back off the woodwork and went clear as Nadine came close.

[/vc_column_text][vc_empty_space][/vc_column][/vc_row][vc_row css_animation="" row_type="row" use_row_as_full_screen_section="no" type="full_width" angled_section="no" text_align="left" background_image_as_pattern="without_pattern"][vc_column][vc_single_image image="2782" img_size="full" add_caption="yes" qode_css_animation=""][/vc_column][/vc_row][vc_row css_animation="" row_type="row" use_row_as_full_screen_section="no" type="full_width" angled_section="no" text_align="left" background_image_as_pattern="without_pattern"][vc_column][vc_column_text]

Villa pushed the Stoke keeper once again as a low hard shot was cleared by the keepers legs keeping it still at 3-0 but it was mostly one way traffic. Villa was awarded a free kick just into the Stoke half as Jodie Hutton lifted the ball into the box Sophie Haywood slid into the box like she was trying to save her phone as she connected with the cross smashing the ball into the net completing a beautiful set piece making it 4-0 to Villa Women.

The next attack came from Villa as a corner was cleared but as it fell to Nadine Hanssen, she hit a Volley with the outside of her boot but it was just to close to the Stoke keeper whose positioning was spot on as he punched it clear and get to the rebound, but fantastic skill by Nadine once again, reminded me of the goal she nearly scored against Charlton away.

Jodie Hutton was in the action again as she chipped the ball through to Charlotte Greengrass who put the ball across to Sophie Haywood but as it broke across the goal after the goalkeeper got a hand to it Charlotte Greengrass was there to prod the ball into the net to give Villa Women the 5-0 lead, and her first goal for the club. with 5 minutes to go Cassie Hyde surged forward and unleashed a beautiful shot which Sian Rogers had to acrobatically tip over the bar, the proof of a truly great keeper is a game where she doesn’t have alot to do but as soon as is called upon she is equal to it. But as I had to shout to cheer for Cassie having the effort as we all love Cassie even though she is on the other team. Jodie Hutton was looking for a goal to finish the game off but as she struck her shot from the edge of the box the keeper for Stoke once again was there to get a hand to it.

The full time whistle went and ended 5-0 to Aston Villa Women. Our first preseason game was a interesting insight to what will be coming for the rest of the season. Everything seems quite positive and that we are starting to move towards this years run.

The new signings looking to bed into the team well without being at the club long. The one thing that was very positive was the way that certain players were used in different roles to show that even in injury we have the back up we need as we will have a physical and long season once again. We are upset a little at losing a few of our players we had a special bond with last season’s team so it hurts more, but as Chris said in Gemma we trust so we will be behind her and team 100% along the way.

We next play on Friday night against Everton at Boldmere with a 7.30pm kick off.

[/vc_column_text][/vc_column][/vc_row]

**Comment by kevinfodness** [comment]
I don't have the handler for those shortcodes locally, so could you link me to the public URL for that article to see what it translates to?

**Comment by Orzolek** [comment]
Sure,

http://since-71.com/match-report-aston-villa-5-0-stoke-city/

**Comment by kevinfodness** [comment]
Sorry for the delay here - we were hard at work on v2 of the plugin, which just shipped yesterday.

I'm somewhat at a loss to explain what Apple is reporting here, as it looks like the content should convert properly after those shortcodes are processed. Can you download the article JSON for one of the failing articles and link or paste it here? You'd go to the Apple News menu item on the left, then find your article, and click Download.

**Comment by Orzolek** [comment]
{"version":"1.7","identifier":"post-3402","language":"en-GB","title":"ANOC Games Match Report: Team GB 2-3 Spain","documentStyle":{"backgroundColor":"#1c1c1c"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"header","layout":"headerPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"http:\/\/since-71.com\/wp-content\/uploads\/2019\/10\/Team-GB.jpg"}],"behavior":{"type":"parallax","factor":0.8}},{"role":"container","layout":{"columnSpan":7,"columnStart":0,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#1c1c1c"},"components":[{"role":"title","text":"ANOC Games Match Report: Team GB 2-3 Spain","format":"html","textStyle":"default-title","layout":"title-layout"},{"role":"byline","text":"by Stuart Barker October 16 at 10:07 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"body","text":"<p>After a near-perfect few days in Qatar, <a href=\"https:\/\/twitter.com\/PerryNortheast\">Perry Northeast<\/a>\u2018s <a href=\"https:\/\/twitter.com\/TeamGB\">Team GB<\/a> comfortably overcame three strong teams in their group to qualify for the semi-finals. They were forced to dig deep to overcome a 5-2 scoreline against Brazil and come back to win 6-5. This victory guaranteed at least a silver medal as they took on Spain in the gold medal play-off.<\/p>","format":"html","textStyle":"dropcapBodyStyle","layout":"body-layout"},{"role":"body","text":"<p>Team GB will have been pleased with their start when former <a href=\"https:\/\/twitter.com\/ChiCityLadiesFC\">Chichester City<\/a> forward, <a href=\"https:\/\/twitter.com\/molly_clarky10\">Molly Clark<\/a>, put her side ahead. <\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Things quickly soured as Spain scored three quickfire goals from <a href=\"https:\/\/www.instagram.com\/loregochi\/?hl=en\">Lorena Asensio<\/a> and <a href=\"https:\/\/www.instagram.com\/carmen.fresneda\/?hl=en\">Carmen Fresneda Morga<\/a>. Asensio scoring two goals with her only two shots of the game. <\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>The second period was a tight affair with no goals for either side. It wasn\u2019t too much of a surprise as Team GB knew that they couldn\u2019t afford to concede again. While Spain knew that they had to be sensible and avoid any errors as they had one hand on the gold medal. <\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Team GB played with more urgency in the third period as they pushed to get back into the game. <a href=\"https:\/\/twitter.com\/bekbarron8\">Rebecca Barron<\/a> pulled one back with a shot that beat <a href=\"https:\/\/www.instagram.com\/lauragallegosilvente\/?hl=en\">Laura Gallego Silvente<\/a>. The La Roja keeper misjudging the bounce of the ball. <\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Sadly for <a href=\"https:\/\/www.instagram.com\/sarahkempson7\/?hl=en\">Sarah Kempson<\/a> and co, they were unable to get the equaliser and it was Spain who picked up the gold medal in the inaugural <a href=\"https:\/\/twitter.com\/AWBG2019\">ANOC World Beach Games<\/a>. Northeast\u2019s team can hold their heads high and be immensely proud of their achievements over the last week. After the success of the beach soccer competition, fingers crossed that we\u2019ll see its inclusion in the Olympics in the near future.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>With a number of the squad currently unattached, there will be no shortage of clubs trying to secure their services for the remainder of the season. <\/p>","format":"html","textStyle":"default-body","layout":"body-layout-last"}]}],"componentTextStyles":{"dropcapBodyStyle":{"textAlignment":"left","fontName":"Georgia","fontSize":17,"tracking":0,"lineHeight":23,"textColor":"#e2e2e2","linkStyle":{"textColor":"#ffe890"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":5,"numberOfCharacters":1,"padding":5,"fontName":"HelveticaNeue-CondensedBold","textColor":"#e2e2e2","numberOfRaisedLines":0}},"default-body":{"textAlignment":"left","fontName":"Georgia","fontSize":17,"tracking":0,"lineHeight":23,"textColor":"#e2e2e2","linkStyle":{"textColor":"#ffe890"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-title":{"fontName":"HelveticaNeue-CondensedBold","fontSize":58,"lineHeight":58,"tracking":-0.01,"textColor":"#ffffff","textAlignment":"center"},"default-byline":{"textAlignment":"center","fontName":"Helvetica-Bold","fontSize":14,"lineHeight":19,"tracking":-0.01,"textColor":"#e2e2e2"}},"textStyles":{"default-tag-code":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"},"default-tag-pre":{"textAlignment":"left","fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f","paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-tag-samp":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"}},"componentLayouts":{"body-layout":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":30}},"headerPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7},"headerBelowTextPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7,"margin":{"top":30,"bottom":0}},"title-layout":{"margin":{"top":30,"bottom":30}},"byline-layout":{"margin":{"top":10,"bottom":10},"columnStart":0,"columnSpan":7}},"metadata":{"thumbnailURL":"http:\/\/since-71.com\/wp-content\/uploads\/2019\/10\/Team-GB.jpg","dateCreated":"2019-10-16T21:07:58+00:00","dateModified":"2019-10-16T21:07:58+00:00","datePublished":"2019-10-16T21:07:58+00:00","canonicalURL":"http:\/\/since-71.com\/anoc-games-match-report-team-gb-2-3-spain\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"2.0.3"},"advertisingSettings":{"frequency":1,"layout":{"margin":{"top":15,"bottom":15}}}}

**Comment by Orzolek** [comment]
Thanks for your continued help. The new version displays this when I click on the "Sections" settings.

**Comment by Orzolek** [comment]
Hello,

Any updates, as we still have no luck publishing. We clean installed the new version of the plugin (and deleted the plugin metadata) and our errors have now changed.

We get:
API: NOT_ALLOWED

and on some we get:
The following components are unsupported by Apple News and were removed:
a
a
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
span
div
div
div
div

**Comment by JoshuaSoileau** [comment]
I am getting `NOT_ALLOWED` errors as well in similar fashion.

**Comment by kevinfodness** [comment]
We just released version 2.1.0 of the plugin, which contains some fixes for HTML parsing. Could you give that a try and let me know if it resolves any of the issues?

Also, the pastes above are rather garbled - if the plugin is still generating bad output that Apple is rejecting, please provide pastebin.com or similar links so I can see the raw text.

Thanks.

**Comment by Orzolek** [comment]
HI Kevin,

Still getting errors, here’s the PasteBin: https://pastebin.com/MdceUYLz

And here is the add-on message:

Many thanks,
Angelo

The following components are unsupported by Apple News and were removed:
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
div
strong
div
div
div
strong
div
div
div

If you need assistance, please reach out for support on WordPress.org <https://wordpress.org/support/plugin/publish-to-apple-news> or GitHub <https://github.com/alleyinteractive/apple-news/issues>.
Dismiss this notice.
There has been an error with the API: NOT_ALLOWED

If you need assistance, please reach out for support on WordPress.org <https://wordpress.org/support/plugin/publish-to-apple-news> or GitHub <https://github.com/alleyinteractive/apple-news/issues>.

**Comment by kevinfodness** [comment]
The API response of `NOT_ALLOWED` refers specifically to one of the following two scenarios:

`NOT_ALLOWED`
* The section you specified does not belong to the given channel. Key path: `data.links.sections.#`.
* Once an article has been published with isPreview set to false, the setting cannot be changed to true. Key path: `data.isPreview`.

ref: https://developer.apple.com/documentation/apple_news/code

The component warnings don't appear to have anything to do with the reason why the article won't publish. You can disable display of those in the plugin settings if they are just adding noise.
