### ISSUE TITLE
Block Support: Cover and Button

### ISSUE THREAD

**Issue by rickalee** [alleyinteractive/apple-news#724]
Cover Blocks are adding .wp-block-cover__inner-container as caption which causes Error.

https://rickal.ee/YEu1DqjL

Button(s) blocks are being stripped - LinkButton component available.
https://developer.apple.com/documentation/apple_news/linkbutton

**Comment by kevinfodness** [comment]
I just released version 2.0.8 which has support for button blocks. Can you confirm?

Cover is a little more complicated, as there isn't an allegory in Apple News Format.

**Comment by kevinfodness** [comment]
Let me clarify my last statement - it shouldn't be causing an error, but adding in full support for the Cover component is a larger undertaking because there isn't a component in ANF that does the same thing, so we'd have to build a JSON structure for it.

**Comment by rickalee** [comment]
@kevinfodness Still seeing button block being stripped in 2.0.8

**Comment by kevinfodness** [comment]
Can you send me the value of `post_content` from the database for an example post that's failing? I'll take a look on my end and see if I can reproduce.

**Comment by rickalee** [comment]
@kevinfodness My apologies, needed to ensure Link Button in theme had settings and 'saved' along with button having URL set. 

I would note buttons are stacking instead of being aligned horizontally. 

https://rickal.ee/8Lu7eomr

**Comment by kevinfodness** [comment]
OK, that's useful info, the new component info isn't present in legacy themes and would need to be added as part of an upgrade process. I hadn't considered that. I can get that in a future version so you don't need to do that manually. That's also going to affect a few other things we added recently, like layouts for audio / video / tables with captions.

Not including the button if it doesn't have a URL set is intentional - if you have a LinkButton component with an invalid URL, Apple will reject the article, so I'm filtering out things like empty string, `#`, etc.

We don't have support for alignment on buttons - are you using a Button Group? Columns?

**Comment by rickalee** [comment]
Using wp:buttons 

https://gist.github.com/rickalee/dbc7d3734e2a7f36b21ddc83fc770717

**Comment by ericdye** [comment]
The Cover block error continues to be an issue for our Newspack publishers using Apple News. The [Cover block](https://wordpress.com/support/wordpress-editor/blocks/cover-block/) is a standard WordPress block that's useful in creating compelling content. We'd love to see some parity on this. 😄

**Comment by cbirdsong** [comment]
Whole paragraphs can go missing from a story if they're located in a cover block, which is a big issue. Even basic support that just strips out the image and ensures the text comes through would go a long way.
